# Generated by Django 4.2.9 on 2024-03-14 22:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timemanagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeentry",
            options={
                "ordering": ["date"],
                "permissions": (("can_view_all_entries", "Can view all entries"),),
            },
        ),
    ]
